version: '3'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "13004:13004"
    env_file:
      - .env.test
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend