# Generated by Django 5.0.1 on 2024-06-09 03:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import products.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('outpath', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=256)),
                ('batch_size', models.IntegerField(default=10)),
                ('learning_rate', models.FloatField(default=1e-05)),
                ('epochs', models.IntegerField(default=200)),
                ('workers', models.IntegerField(default=0)),
                ('bands', models.IntegerField(default=3)),
                ('classes', models.IntegerField(default=2)),
                ('model', models.CharField(default='unet', max_length=20)),
                ('encoder', models.CharField(default='resnet101', max_length=50)),
                ('loss', models.CharField(default='dice', max_length=50)),
                ('optimizer', models.CharField(default='adamw', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelsTrained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('pth_path', models.CharField(blank=True, max_length=200, null=True)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('train_csv', models.CharField(blank=True, max_length=250, null=True)),
                ('test_csv', models.CharField(blank=True, max_length=250, null=True)),
                ('parameters', models.CharField(blank=True, max_length=250, null=True)),
                ('file_locations', models.FileField(blank=True, null=True, upload_to=products.utils.get_upload_files)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='RequestBounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mask', models.CharField(blank=True, max_length=200, null=True)),
                ('done', models.BooleanField(default=False)),
                ('bounds', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PROCESSING', max_length=10)),
                ('response', models.JSONField(blank=True, null=True)),
                ('png', models.FileField(blank=True, null=True, upload_to='')),
                ('bounds_png', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.modelstrained')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
