# Generated by Django 4.1 on 2023-05-08 20:14

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('outpath', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=256)),
                ('batch_size', models.IntegerField(default=10)),
                ('learning_rate', models.FloatField(default=1e-05)),
                ('epochs', models.IntegerField(default=200)),
                ('workers', models.IntegerField(default=0)),
                ('bands', models.IntegerField(default=3)),
                ('classes', models.IntegerField(default=2)),
                ('model', models.CharField(default='unet', max_length=20)),
                ('encoder', models.CharField(default='resnet101', max_length=50)),
                ('loss', models.CharField(default='dice', max_length=50)),
                ('optimizer', models.CharField(default='adam', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='modelstrained',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='modelstrained',
            name='file_locations',
            field=models.FileField(blank=True, null=True, upload_to=products.models.get_upload_files),
        ),
        migrations.AddField(
            model_name='modelstrained',
            name='parameters',
            field=models.FileField(blank=True, null=True, upload_to=products.models.get_upload_files),
        ),
        migrations.AddField(
            model_name='modelstrained',
            name='test_csv',
            field=models.FileField(blank=True, null=True, upload_to=products.models.get_upload_files),
        ),
        migrations.AddField(
            model_name='modelstrained',
            name='train_csv',
            field=models.FileField(blank=True, null=True, upload_to=products.models.get_upload_files),
        ),
        migrations.AddField(
            model_name='modelstrained',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelstrained',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
