# Generated by Django 5.0.1 on 2024-06-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelstrained',
            name='file_locations',
        ),
        migrations.RemoveField(
            model_name='modelstrained',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='modelstrained',
            name='pth_path',
        ),
        migrations.RemoveField(
            model_name='modelstrained',
            name='test_csv',
        ),
        migrations.RemoveField(
            model_name='modelstrained',
            name='train_csv',
        ),
    ]
