# Generated by Django 4.1 on 2023-05-09 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_trainmodel_modelstrained_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprocess',
            name='date_requested',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='requestprocess',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
