# Generated by Django 4.1 on 2024-01-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_modelstrained_pth_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainmodel',
            name='optimizer',
            field=models.CharField(default='adamw', max_length=50),
        ),
    ]
