# Generated by Django 4.1 on 2024-02-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_requestvisualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestvisualization',
            name='png',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
