# Generated by Django 4.1 on 2024-02-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_requestvisualization_png'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestvisualization',
            name='bounds',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
