# Generated by Django 4.1 on 2024-02-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_requestvisualization_bounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestvisualization',
            name='png',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
