# Generated by Django 5.0.1 on 2024-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_requestvisualization_png'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprocess',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PROCESSING', max_length=10),
        ),
    ]
