# Generated by Django 5.0.1 on 2024-06-05 21:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_requestprocess_bounds_png_requestprocess_png'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mask', models.CharField(blank=True, max_length=200, null=True)),
                ('done', models.BooleanField(default=False)),
                ('bounds', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('DONE', 'Done'), ('ERROR', 'Error')], default='PROCESSING', max_length=10)),
                ('response', models.JSONField(blank=True, null=True)),
                ('png', models.FileField(blank=True, null=True, upload_to='')),
                ('bounds_png', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.modelstrained')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RequestVisualization',
        ),
    ]
