# Generated by Django 4.1 on 2023-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TilesProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField()),
                ('size', models.BigIntegerField()),
                ('product', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tile',
                'verbose_name_plural': 'Tiles',
            },
        ),
    ]
