# Generated by Django 4.1 on 2023-04-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tilesprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilesprocessed',
            name='date_image',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
