# Generated by Django 4.1 on 2023-04-25 17:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tilesprocessed_date_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilesprocessed',
            name='poly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
