# Generated by Django 5.1.3 on 2024-12-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tilesprocessed',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='tilesprocessed',
            name='size',
        ),
    ]
