# Generated by Django 5.1.3 on 2024-12-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_tilesprocessed_last_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tilesprocessed',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
