# Generated by Django 5.0.1 on 2024-06-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request',
            field=models.IntegerField(default=0),
        ),
    ]
